# Generated by Django 2.2.2 on 2019-07-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(max_length=10, verbose_name='Subject1')),
                ('sub2', models.IntegerField(max_length=10, verbose_name='Subject2')),
                ('sub3', models.IntegerField(max_length=10, verbose_name='Subject3')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30, verbose_name='Teacher Name')),
            ],
        ),
    ]
