# Generated by Django 2.2.2 on 2019-07-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student'),
        ),
    ]
