# Generated by Django 2.2.2 on 2019-07-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_marks_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='sid',
        ),
        migrations.AddField(
            model_name='student',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
    ]
