# Generated by Django 2.2.2 on 2019-07-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190702_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(blank=True, choices=[('Jp', 'Java programming'), ('Cp', 'C programming'), ('C++p', 'C++ programming'), ('Pp', 'Python')], max_length=30, null=True, verbose_name='Book Name')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student')),
            ],
        ),
    ]
